### ISSUE TITLE
Stuck on Cookies Popup

### ISSUE THREAD

**Issue by DartMouthWrld** [BhaskarPanja93/View-Bot-Client#54]
The bot can't seem to get past the cookie notification on linkvertise.

**Comment by BhaskarPanja93** [comment]
sorry i was inactive for a while, let me check if something changed, and i will modify the code accordingly
@DartMouthWrld

**Comment by DartMouthWrld** [comment]
Alright, I appreciate it

**Comment by BhaskarPanja93** [comment]
Okay the bot isn't stuck on Cookie Popup, actually what must have happened is, the VM reached the captcha solving page, was waiting for captcha, and before it started with captcha the website gave the Cookie Popup, so the bot is now just waiting forever for the captcha, I am assuming this, because someone said this happened to them too. If I see myself what happened, i will re-write the code accordingly. Feel free to send me a video of this occurrence if it happens to you, I will modify the code.
@DartMouthWrld

**Comment by DartMouthWrld** [comment]
alright thanks
